version: "3.9"

x-airflow-common: &airflow-common
  build: .

  # image: apache/airflow:2.9.3-python3.10
  environment:
    AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "True"

    # Airflow metadata DB (points to the "airflow" database)
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASSWORD}@postgres:5432/${AIRFLOW_DB_NAME}
    
    # Executor & timezone
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__DEFAULT_TIMEZONE: America/Toronto
    
    # Admin bootstrap (for airflow-init only; harmless for others)
    _AIRFLOW_WWW_USER_USERNAME: ${AIRFLOW_ADMIN_USERNAME}
    _AIRFLOW_WWW_USER_PASSWORD: ${AIRFLOW_ADMIN_PASSWORD}
  
    # Make sure we can install extras at container start
    _PIP_ADDITIONAL_REQUIREMENTS: "psycopg2-binary==2.9.9 pandas==1.5.3 sqlalchemy==1.4.52 pyspark==3.5.1 rapidfuzz==3.9.6 apache-airflow-providers-postgres==5.8.0"

    # Mounting input data folder into the Airflow Container
    PYTHONPATH: /opt/airflow/src:/opt/airflow/dags
  
  volumes:
    - ./airflow/dags:/opt/airflow/dags
    - ./airflow/logs:/opt/airflow/logs
    - ./airflow/include:/opt/airflow/include
    - ./src:/opt/airflow/src
    - ./data/input:/opt/data/input
    - ./data/outputs:/opt/data/outputs
    - ./jars:/opt/jars

  user: "${AIRFLOW_UID:-50000}:0"
  depends_on:
    postgres:
      condition: service_healthy

services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_SUPERUSER}
      POSTGRES_PASSWORD: ${POSTGRES_SUPERPASS}
      POSTGRES_DB: postgres
    ports:
      - "55432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_SUPERUSER} -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
  
  airflow-init:
    #image: apache/airflow:2.9.3
    <<: *airflow-common
    container_name: airflow-init
    depends_on:
      postgres:
        condition: service_healthy 
    
    entrypoint: bash -c "
      airflow db migrate && \
      airflow users create \
        --username ${AIRFLOW_ADMIN_USERNAME} \
        --firstname Admin \
        --lastname User \
        --role Admin \
        --email ${AIRFLOW_ADMIN_EMAIL} \
        --password ${AIRFLOW_ADMIN_PASSWORD} || true && \
      airflow connections delete postgres_warehouse || true && \
      airflow connections add postgres_warehouse \
        --conn-type postgres \
        --conn-host postgres \
        --conn-port 5432 \
        --conn-schema ${WAREHOUSE_DB_NAME} \
        --conn-login ${WAREHOUSE_DB_USER} \
        --conn-password ${WAREHOUSE_DB_PASSWORD} || true"
        #--conn-uri postgresql+psycopg2://${WAREHOUSE_DB_USER}:${WAREHOUSE_DB_PASSWORD}@postgres:5432/${WAREHOUSE_DB_NAME} || true"

    # # Mounting project folders into the Airflow Container
    # volumes:
    #   - ./airflow/dags:/opt/airflow/dags
    #   - ./airflow/logs:/opt/airflow/logs
    #   - ./airflow/include:/opt/airflow/include
    #   - ./src:/opt/airflow/src
    #   - ./data:/opt/airflow/data
    
    # user: "${AIRFLOW_UID:-50000}:0"
        
  airflow-webserver:
    <<: *airflow-common
    container_name: airflow-webserver
    depends_on:
      postgres:
        condition: service_healthy
    command: webserver
    ports:
      - "8080:8080"
      
  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow-scheduler
    depends_on:
      postgres:
        condition: service_healthy
    command: scheduler
    
volumes:
  pgdata: